name: C/C++ CI

on:
  push:
    branches:
    - main
    - master
    - stable
    - release
  pull_request:
    branches:
    - dev
    - devel/*
    - test/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make debug
      run: make debug
    - name: make build
      run: make build
